tasks = [
    "Pretend you're a mind reader and predict someone’s next sentence.",
    "Casually mention you've won an obscure contest.",
    "Ask someone for directions to a place that doesn't exist.",
    "Compliment someone on their shoes twice in one conversation.",
    "Drop a pen and ask someone to pick it up for you.",
    "Make up a completely random fact about a common object.",
    "Whisper every time you speak for the next 5 minutes.",
    "Convince someone you’ve lost your sense of smell.",
    "Tell a story that didn’t happen, and see if anyone notices.",
    "Bring up a random topic and act like it’s the most important subject.",
    "Start humming a random tune and see if others join.",
    "Pretend to forget someone’s name and ask them what it is again.",
    "Mention that you can hear something others can’t.",
    "Pick up something that isn’t yours and act like you lost it.",
    "Tell someone you’ve been learning a new language and say a made-up phrase.",
    "Look confused after someone says something simple.",
    "Ask someone to guess a number between 1 and 100, but never reveal the correct answer.",
    "Pretend you’re getting an important phone call and act serious.",
    "Ask someone to hold something for you, but never take it back.",
    "Tell someone a word has lost all meaning to you and repeat it multiple times.",
    "Convince someone you're afraid of an everyday object.",
    "Ask someone if they’ve ever had a paranormal experience, and act completely serious.",
    "Pretend you’ve just realized something amazing and share a mundane fact.",
    "Compliment someone on something small and keep bringing it up.",
    "Stand up, stretch, and sit back down without explanation.",
    "Tell someone you’ve always wanted to visit a country that doesn’t exist.",
    "Keep glancing at a door or window suspiciously.",
    "Ask someone if they’ve noticed the room feels different today.",
    "Pretend to forget how to use a common object.",
    "Mention an imaginary friend and ask if anyone else can see them.",
    "Apologize to someone for a ‘mistake’ you didn’t make.",
    "Convince someone that a random object is voice-activated.",
    "Repeat someone’s name often in a conversation.",
    "Tell someone you've learned how to read minds, but refuse to demonstrate.",
    "Switch the topic of conversation whenever someone asks a direct question.",
    "Pretend to be deeply interested in a random part of the room.",
    "Ask someone if they’ve ever thought about becoming a professional athlete.",
    "Act like you’ve never heard of something common, like a TV or phone.",
    "Pretend you’re confused about a simple task, like tying your shoes.",
    "Start telling a long story and stop halfway through, then change the topic.",
    "Ask someone if they believe in time travel, then act like you’ve done it.",
    "Drop something small and keep picking it up repeatedly.",
    "Use a common word incorrectly in multiple conversations.",
    "Convince someone that a random object is broken and can’t be used.",
    "Ask someone to guess your middle name and never confirm if they’re right.",
    "Act like you’re suddenly bad at counting simple numbers.",
    "Tell someone you’re working on a secret project, but give no details.",
    "Make an object ‘disappear’ by hiding it in your pocket and acting amazed.",
    "Ask someone if they can guess what you had for breakfast.",
    "Pretend you’re allergic to something harmless like air or water.",
    "Laugh randomly during a serious conversation.",
    "Mention you’ve seen someone do something amazing, but give no context.",
    "Ask someone if they’ve ever seen a UFO, then act suspicious.",
    "Pretend you don’t know the date and keep asking others for the correct day.",
    "Ask someone if they’ve ever met a famous person, then tell an imaginary story.",
    "Act like you’re deeply considering something when someone speaks.",
    "Ask someone if they’ve seen your pet (that doesn’t exist).",
    "Pretend you’ve never heard of a very common place or object.",
    "Convince someone that you’re an expert in a random, made-up subject.",
    "Pretend to misunderstand something simple and ask for an explanation.",
    "Start talking about a movie that doesn’t exist, but act like it’s famous.",
    "Ask someone to hold your phone, then pretend you lost it.",
    "Repeat the same question to multiple people until someone notices.",
    "Convince someone that a common object is incredibly rare.",
    "Ask someone to help you with something simple, then act confused.",
    "Ask someone to guess your favorite color and change it every time.",
    "Start every sentence for the next five minutes with ‘Did you know?’",
    "Ask someone if they remember something they’ve never experienced.",
    "Pretend to be an expert on something you know nothing about.",
    "Compliment someone on something imaginary, like their ‘aura.’",
    "Pretend to forget where you are and ask someone for directions.",
    "Act surprised when someone says something obvious.",
    "Pretend you’ve invented a new gadget and describe it vaguely.",
    "Ask someone if they’ve heard about a news event you’ve made up.",
    "Compliment someone on how well they did something, even if they didn’t do it.",
    "Pretend you’ve forgotten how to hold a cup properly.",
    "Ask someone if they’ve heard a strange noise, then act concerned.",
    "Tell someone you’ve just realized the meaning of life, but never explain.",
    "Repeat the same word multiple times in a conversation until someone notices.",
    "Ask someone if they’ve ever met a ghost and act serious.",
    "Convince someone that you’ve switched your dominant hand.",
    "Pretend to yawn repeatedly and see if others yawn too.",
    "Ask someone if they’ve ever visited a place that doesn’t exist.",
    "Tell someone you’ve been thinking a lot about ‘the universe,’ then say nothing else.",
    "Pretend to write a letter to someone imaginary and ask for their advice.",
    "Ask someone if they can guess your birthday and never confirm it.",
    "Talk about a book or show that doesn’t exist, and act like it’s very popular.",
    "Pretend you’re searching for something small, then give up suddenly.",
    "Tell someone you’ve just seen something amazing, but refuse to explain.",
    "Ask someone if they’ve ever had an imaginary friend, and act serious.",
    "Start talking about a hobby you don’t have, and describe it in detail.",
    "Pretend to forget how to use a door and ask for help.",
    "Convince someone that you’re secretly famous, but don’t give details.",
    "Mention you’ve been working on an important project, but give no details.",
    "Ask someone what they think of your new invention, but never show it to them.",
    "Pretend to be very interested in the weather for the next five minutes.",
    "Ask someone if they’ve ever heard of a food item you just made up.",
    "Tell someone you’ve just been to an incredible place that doesn’t exist.",
    "Pretend you’ve suddenly forgotten what year it is and keep asking others.",
    "Ask someone to guess a number between 1 and 10, but keep changing it.",
    "Convince someone that you’ve never heard of a very common thing, like a car."
]
